### ISSUE TITLE
make navbar transparent

### ISSUE THREAD

**Issue by jovo** [jovo/jovo.github.com#10]
i tried a few ways and failed.

**Comment by ronboger** [comment]
it didn't look great transparent, so i made it opaque and it looks better

**Comment by jovo** [comment]
can i see on a dev branch please?

On Sun, May 24, 2015 at 1:04 AM, ron boger notifications@github.com wrote:

>  Closed #10 https://github.com/jovo/jovo.github.com/issues/10.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/jovo.github.com/issues/10#event-312488530.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
