### ISSUE TITLE
make website look awesome in iphone & ipad

### ISSUE THREAD

**Issue by jovo** [jovo/jovo.github.com#11]

**Comment by ronboger** [comment]
it does

**Comment by jovo** [comment]
see my email.
looks shitty on my phone.

On Sat, May 23, 2015 at 11:52 PM, ron boger notifications@github.com
wrote:

>  it does
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/jovo.github.com/issues/11#issuecomment-104975944
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by ronboger** [comment]
lol what? bootstrap is supposed to make it mobile responsive!

**Comment by jovo** [comment]
maybe i fucked it up?

On Sat, May 23, 2015 at 11:59 PM, ron boger notifications@github.com
wrote:

>  lol what? bootstrap is supposed to make it mobile responsive!
> On May 23, 2015 8:57 PM, "joshua vogelstein" notifications@github.com
> wrote:
> 
> > see my email.
> > looks shitty on my phone.
> > 
> > On Sat, May 23, 2015 at 11:52 PM, ron boger notifications@github.com
> > wrote:
> > 
> > > it does
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/jovo/jovo.github.com/issues/11#issuecomment-104975944
> > > 
> > > .
> > 
> > ## 
> > 
> > the glass is all full: half water, half air.
> > openconnecto.me, jovo.me, office hours
> > <
> > 
> > https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
> > 
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/jovo/jovo.github.com/issues/11#issuecomment-104976101>
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/jovo.github.com/issues/11#issuecomment-104976120
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by ronboger** [comment]
I'll check the commit history...

**Comment by jovo** [comment]
also looks shitty when the window has certain sizes, eg:
https://www.dropbox.com/s/tpkexfl3nqauuic/Screenshot%202015-05-24%2001.01.53.png?dl=0

**Comment by ronboger** [comment]
i think it looks nice

**Comment by jovo** [comment]
it is better, there are still 2 problems:

(1) the menubar should never be more than 1 row
(2) the brain image is still hella big, so big that it is impossible to tell what it is.

**Comment by ronboger** [comment]
(1) done
(2) i don't wanna do that
