### ISSUE TITLE
add pic of me in the about me section

### ISSUE THREAD

**Issue by jovo** [jovo/jovo.github.com#12]

**Comment by ronboger** [comment]
i like the picture of you jumping on the ocp page better, but done. look at the code please

**Comment by jovo** [comment]
fair point. i'll think about putting in the other one.

On Sun, May 24, 2015 at 12:55 AM, ron boger notifications@github.com
wrote:

>  i like the picture of you jumping on the ocp page better, but done. look
> at the code please
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/jovo.github.com/issues/12#issuecomment-104979406
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
