### ISSUE TITLE
make navbar 'close' after selecting link in iphone

### ISSUE THREAD

**Issue by jovo** [jovo/jovo.github.com#14]

**Comment by ronboger** [comment]
functions as it should, it needs to stay open if the user clicks the wrong scroll button. then you close it by pressing the 3 buttons

**Comment by jovo** [comment]
i want to minimize the expected # of clicks to navigate.
if it auto contracts, and the user goes to the right place, it is n=2 per navigation,
if it doesn't, and the user goes to the right place, it is n=3 per navigation.

on the other hand, if the user goes to the wrong place first, and then corrects on the 2nd try,
and it auto-contracts, n=4,
and if it doesn't, n=4.

thus, your design decision never saves the user clicks.

correct me if i'm wrong?

**Comment by ronboger** [comment]
ok i like it better that way too, added some js that does the job. if u
resize the picture i'll write the code
