### ISSUE TITLE
make background image be small in iphone/ipad

### ISSUE THREAD

**Issue by jovo** [jovo/jovo.github.com#15]

**Comment by jovo** [comment]
@gkiar @ronnyb29 refused to make your image look beautiful on the iphone :(

**Comment by gkiar** [comment]
booooo

## 

Greg Kiar gkiar07@gmail.com

**Comment by gkiar** [comment]
I think it looks cool!

![2015-05-24 15 38 08](https://cloud.githubusercontent.com/assets/4883288/7788469/d70c91d4-0209-11e5-9677-aae264636937.png)

**Comment by jovo** [comment]
is that an image from your iphone?

On Sun, May 24, 2015 at 11:41 AM, Greg Kiar notifications@github.com
wrote:

>  I think it looks cool!
> 
> [image: 2015-05-24 15 38 08]
> https://cloud.githubusercontent.com/assets/4883288/7788469/d70c91d4-0209-11e5-9677-aae264636937.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/jovo.github.com/issues/15#issuecomment-105028260
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by gkiar** [comment]
Ya, just took the screenshot ~5 min ago.

## 

Greg Kiar gkiar07@gmail.com

**Comment by jovo** [comment]
@gkiar can you resize the pic, and @ronnyb29 will write the code?
after that, i believe we are done with this!!!

**Comment by jovo** [comment]
@gkiar i'll try first, and if i fail, i'll ask for help.

**Comment by gkiar** [comment]
OK, I've made a vertical one and uploaded it to the google drive already
(labeled ocp_phone_wallpaper_light.png) - so, help is already there should
you need it!

## 

Greg Kiar gkiar07@gmail.com

On Sun, May 24, 2015 at 4:04 PM, joshua vogelstein <notifications@github.com

**Comment by ronboger** [comment]
no issues left:)

**Comment by jovo** [comment]
but this still doesn't work on my iphone :(

On Monday, June 1, 2015, ron boger notifications@github.com wrote:

>  no issues left:)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/jovo.github.com/issues/15#issuecomment-107319160
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by ronboger** [comment]
picture please? works well on mine
