### ISSUE TITLE
CSS hack uglifies display on mid-sized screens

### ISSUE THREAD

**Issue by j6k4m8** [jovo/jovo.github.com#18]
![image](https://cloud.githubusercontent.com/assets/693511/7799810/19c6b412-02d9-11e5-8101-737dcb4bae24.png)

This is from the `<!-- ^ you better look at this comment jovo because this css hack makes it line up -->` hack.

**Comment by jovo** [comment]
@j6k4m8 can you fix it easily?

**Comment by j6k4m8** [comment]
Probably, but I don't want to futz around too much if @ronnyb29 is on a roll. If he gives the go-ahead I can probably whip something together in a few minutes.

**Comment by jovo** [comment]
he happily requests that you do :)

**Comment by ronboger** [comment]
yes please, my way is currently super ghetto, i'd love to see how this is done properly

**Comment by ronboger** [comment]
done
