### ISSUE TITLE
scrolling thing, where is my code from earlier? i see no dev branch...

### ISSUE THREAD

**Issue by ronboger** [jovo/jovo.github.com#2]

**Comment by jovo** [comment]
pushed.

On Wed, Apr 22, 2015 at 3:03 PM, ron boger notifications@github.com wrote:

>  —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/jovo.github.com/issues/2.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
