### ISSUE TITLE
add MedHacks (pending it going well)

### ISSUE THREAD

**Issue by ronboger** [jovo/jovo.github.com#21]

**Comment by jovo** [comment]
make a pull request :)

On Thu, Oct 1, 2015 at 2:20 AM, ron boger notifications@github.com wrote:

> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/jovo.github.com/issues/21.

## 

the glass is all full:  half water, half air.
openconnecto.me, medhacks http://medhacks.org/, calendar
https://www.google.com/calendar/embed?src=afr9t36kknt629jh4omun20n90%40group.calendar.google.com&ctz=America/New_York

**Comment by ronboger** [comment]
what section does this go in? about me or section of its own
