### ISSUE TITLE
make background @gkiar's thing

### ISSUE THREAD

**Issue by jovo** [jovo/jovo.github.com#4]

**Comment by ronboger** [comment]
i feel like this is not the intention...
![image](https://cloud.githubusercontent.com/assets/8752064/7553208/3c1f2a7c-f6b7-11e4-8b1e-c829f2f49f2e.png)

maybe you want something like the medhacks site?

**Comment by jovo** [comment]
i vote move the menu bar to the top first,
then we can play with background options.

On Sun, May 10, 2015 at 1:53 AM, ron boger notifications@github.com wrote:

>  i feel like this is not the intention...
> [image: image]
> https://cloud.githubusercontent.com/assets/8752064/7553208/3c1f2a7c-f6b7-11e4-8b1e-c829f2f49f2e.png
> 
> maybe you want something like the medhacks site?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/jovo.github.com/issues/4#issuecomment-100589642.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by jovo** [comment]
doesn't seem done?

On Fri, May 15, 2015 at 1:35 AM, ron boger notifications@github.com wrote:

>  Closed #4 https://github.com/jovo/jovo.github.com/issues/4.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/jovo.github.com/issues/4#event-305524983.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by ronboger** [comment]
i thought i pushed it like 5 days ago... hold on lemme check

**Comment by ronboger** [comment]
on my windows partition, never pushed and switched to experimental branch... time to boot back from ubuntu

**Comment by ronboger** [comment]
yeah, just forgot to push on windows, check it out now

**Comment by jovo** [comment]
nice.

On Fri, May 15, 2015 at 2:33 AM, ron boger notifications@github.com wrote:

>  yeah, just forgot to push on windows, check it out now
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/jovo.github.com/issues/4#issuecomment-102283248.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
