### ISSUE TITLE
add copyright

### ISSUE THREAD

**Issue by jovo** [jovo/jovo.github.com#5]

**Comment by ronboger** [comment]
ima just make the website either look like this:

http://ironsummitmedia.github.io/startbootstrap-half-slider/

or this:

http://ironsummitmedia.github.io/startbootstrap-business-casual/

with lowercase letters of course

thoughts?

**Comment by ronboger** [comment]
actually i don't like either of those and they don't have the slidey thing.
but i will overhaul it

**Comment by jovo** [comment]
me neither.
i don't think we need an overhaul, just a copyright for this todo

On Fri, May 8, 2015 at 5:54 PM, ron boger notifications@github.com wrote:

>  actually i don't like either of those and they don't have the slidey
> thing.
> but i will overhaul it
> 
> On Fri, May 8, 2015 at 5:53 PM, Ron Boger ronboger@gmail.com wrote:
> 
> > ima just make the website either look like this:
> > 
> > http://ironsummitmedia.github.io/startbootstrap-half-slider/
> > 
> > or this:
> > 
> > http://ironsummitmedia.github.io/startbootstrap-business-casual/
> > 
> > with lowercase letters of course
> > 
> > thoughts?
> > 
> > On Fri, May 8, 2015 at 1:38 PM, joshua vogelstein <
> > notifications@github.com> wrote:
> > 
> > > Assigned #5 https://github.com/jovo/jovo.github.com/issues/5 to
> > > @ronnyb29 https://github.com/ronnyb29.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/jovo/jovo.github.com/issues/5#event-300458225.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/jovo.github.com/issues/5#issuecomment-100378156.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
