### ISSUE TITLE
choose a cool icon for jovo.me to show up next to title on the top of the browser

### ISSUE THREAD

**Issue by ronboger** [jovo/jovo.github.com#6]
like the git cat right next to the title of this tab "choose a cool..."

a good choice would be like the vector graphic of the brain that greg made

on my site ronbger.me it's a stupid plane with a green background

email to me and i'll make it the icon for the page

**Comment by jovo** [comment]
@gkiar made a favicon.
i invited you to the folder that has it.
love it.
