### ISSUE TITLE
add favicon

### ISSUE THREAD

**Issue by jovo** [jovo/jovo.github.com#7]

**Comment by ronboger** [comment]
pushed but...

fav icon looks off, background needs to be transparent, not white

**Comment by ronboger** [comment]
made new ico that's better, pushed to drive and here

**Comment by jovo** [comment]
looks awesome.

On Fri, May 15, 2015 at 2:36 PM, ron boger notifications@github.com wrote:

>  Closed #7 https://github.com/jovo/jovo.github.com/issues/7.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/jovo.github.com/issues/7#event-306109321.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
