### ISSUE TITLE
remove image from apl and clease movie, they block the beautiful background now

### ISSUE THREAD

**Issue by jovo** [jovo/jovo.github.com#8]

**Comment by ronboger** [comment]
i'm not a fan of this change in principle. website needs more color, or at least a blurb at the top about who you are

**Comment by jovo** [comment]
i moved 'philosophy' up to the top to deal with that.
do you have a better idea?

On Fri, May 15, 2015 at 12:20 PM, ron boger notifications@github.com
wrote:

>  i'm not a fan of this change in principle. website needs more color, or
> at least a blurb at the top about who you are
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/jovo.github.com/issues/8#issuecomment-102451819.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by ronboger** [comment]
what about having your github picture on the left of philosophy?

**Comment by ronboger** [comment]
the other thing to consider is making a new section entirely (with a picture of you) saying something along the lines of "hello my name is jovo and i'm an assistant prof at jhu... , etc"

**Comment by jovo** [comment]
maybe. let's move the menubar to the top, and then see.

On Fri, May 15, 2015 at 1:36 PM, ron boger notifications@github.com wrote:

>  what about having your github picture on the left of philosophy?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/jovo.github.com/issues/8#issuecomment-102465396.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
